{% set name = "opentelemetry-instrumentation-httpx" %}
{% set version = "0.53b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_httpx-{{ version }}.tar.gz
  sha256: aa8636ad704a99c6dcb73b649035d820506e93d5a80e45254fa435f131611a9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.53b1
    - opentelemetry-semantic-conventions ==0.53b1
    - opentelemetry-util-http ==0.53b1
    # - wrapt <2.0.0,>=1.0.0
    # - httpx >=0.18.0
    # - wrapt <2.0.0,>=1.0.0
    # - httpx >=0.18.0
    # - wrapt <2.0.0,>=1.0.0
    # - httpx >=0.18.0
    # - wrapt <2.0.0,>=1.0.0
    # - httpx >=0.18.0
    # - wrapt <2.0.0,>=1.0.0
    # - httpx >=0.18.0
    # - wrapt <2.0.0,>=1.0.0
    # - httpx >=0.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx
  summary: OpenTelemetry HTTPX Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-semantic-conventions
    - conda-forge/opentelemetry-util-http
