{% set name = "opentelemetry-instrumentation-httpx" %}
{% set version = "0.50b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_httpx-{{ version }}.tar.gz
  sha256: 0072d1d39552449c08a45a7a0db0cd6af32c85205bd97267b2a272fc56a9b438

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.50b0
    - opentelemetry-semantic-conventions ==0.50b0
    - opentelemetry-util-http ==0.50b0
    # - wrapt <2.0.0,>=1.0.0
    # - httpx >=0.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx
  summary: OpenTelemetry HTTPX Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-semantic-conventions
    - conda-forge/opentelemetry-util-http
