{% set name = "opentelemetry-instrumentation-httpx" %}
{% set version = "0.43b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_httpx-{{ version }}.tar.gz
  sha256: 29d7465058d9bb6bb24e5be230fe533f599d35995f3b89ede9ce557cd06c3356

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.43b0
    - opentelemetry-semantic-conventions ==0.43b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx
  summary: OpenTelemetry HTTPX Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
