{% set name = "opentelemetry-instrumentation-httpx" %}
{% set version = "0.45b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_httpx-{{ version }}.tar.gz
  sha256: 2e9913ca4c568767cf7bb5facab4d22e1dc65ea01ad0b6b6f77b5fcee136fb1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.45b0
    - opentelemetry-semantic-conventions ==0.45b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx >=0.18.0
    # - opentelemetry-util-http ==0.45b0
    # - httpx >=0.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx
  summary: OpenTelemetry HTTPX Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
