{% set name = "opentelemetry-instrumentation-httpx" %}
{% set version = "0.38b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_httpx-{{ version }}.tar.gz
  sha256: 6fc4ce0fd67132151d719e8b31500cf8cc1cdf11976609ccb960849cc7e34487

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.38b0
    - opentelemetry-semantic-conventions ==0.38b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-httpx 
    # - httpx <=0.23.0,>=0.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx
  summary: OpenTelemetry HTTPX Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
